[YDBOcto#1069] In case of outer joins, ignore NULLs for Computed Expressions
A user reported this error:

```
Error: ERROR: YottaDB error:
151027986,WARD+6^DGPMUTL,%YDB-E-ZYSQLNULLNOTVALID, $ZYSQLNULL cannot be used as an integer, numeric, gvn subscript/value or lock subscript
SQLState:  XX000
ErrorCode: 0
```

A sample query that would cause the error on VEHU Image:

```sql
SELECT
p.primary_long_id AS "MRN",
p.name AS "Patient Name",
pm.ward_at_discharge AS "Ward at Discharge",
COALESCE(CAST(pm1.date_time AS TEXT),'0') AS "Admission Date",
pm1.length_of_stay AS "Length Of Stay",
fmt.name AS "Movement Type"
FROM patient AS p
LEFT JOIN patient_movement AS pm on p.patient_id = pm.patient
LEFT JOIN patient_movement AS pm1 on pm.admission_check_in_mov = pm1.patient_movement_id
LEFT JOIN facility_movement_type AS fmt ON pm.type_of_movement = fmt.facility_movement_type_id
LEFT JOIN mas_movement_tran_type AS mmtt ON pm.transaction = mmtt.mas_movement_tran_type_id;
```

Solution: OUTER JOINs in Octo send NULLs as the value of the fields in some
circumstances. Since some the fields are not "real" fields but rather
computed fields, the code to handle computed fields need to be cut short
if NULL is sent as the intial value of the field.